### ISSUE TITLE
Players can see invisible tokens

### ISSUE THREAD

**Issue by juan-r-apolinario** [League-of-Foundry-Developers/simplefog#10]
![image](https://user-images.githubusercontent.com/8976433/102704246-b0c1a200-4257-11eb-968a-61ead6cd68fc.png)
This is the player view. Every token that has its visibility toggle set to "invisible" can be seen by every player.

In this screenshot the only active module is SimpleFog 0.1.16. Without the module, the invisible tokens works as intended.

Edit: grammar

**Comment by juan-r-apolinario** [comment]
![image](https://user-images.githubusercontent.com/8976433/102704583-1748bf00-425c-11eb-954e-2180607f0fe2.png)
Same place, same player, no modules.

**Comment by crhampton1** [comment]
Yikes! I'll take a look!

**Comment by JJBocanegra** [comment]
I'm having this same problem and is a big one :( 

It just happen when I reveal an area with an invisible token inside. If I move the token there after it's revealed, the token is still invisible.

**Comment by crhampton1** [comment]
Okay, I could not replicate, no matter what I did the hidden stayed hidden and the visible stayed visible. However, I think I found the issue and it was in a feature that hasn't worked since Foundry updated their new layer system, so I just removed it. Can you give it a try and see if you still have issues. I have a few other ideas if that doesn't work.

**Comment by JJBocanegra** [comment]
It works for me now 😄 👍

**Comment by crhampton1** [comment]
I have had a few mention that they are not having this problem anymore. I am going to go ahead and close this but if it happens again feel free to reopen!! Thanks!
