### ISSUE TITLE
Unable to enable fog of war on v11

### ISSUE THREAD

**Issue by jasonxbergman** [League-of-Foundry-Developers/simplefog#107]
I just upgraded to Foundry v11, and I'm unable to enable fog of war. It looks enabled, but I'm unable to hide anything.

**Comment by Conandy1970** [comment]
@jasonxbergman it isn't supporting V11 yet. 

I'd love to hear the Dev's idea on when support for V11 will be issued.  Simple Fog is the one feature I rely upon more than anything in Foundry, and I cannot upgrade to new versions of Foundry without SF being implemented.  

It is sad that this far into the dev cycle of Foundry, that they still rely upon independent devs to do something as fundamental as simple fog.

**Comment by UranusBytes** [comment]
I do not have an eta on when v11 will be supported.  I have yet to even try to install v11 or look to see what may have changed.  Hopefully I will have some time in the next month or so.  I welcome someone from the community taking the lead on v11 support.

I too agree that the functionality of simplefog should be part of the Foundry core...  :cry:

**Comment by macskay** [comment]
I had a look into this and after some digging around I found that the Pixi.js version has been updated with Foundry v11, leading to an update of the `canvas.app.renderer.render` function. I updated the `composite` function in `MaskLayer.ts` to reflect the changes and pass in the options in the expected way.

**Comment by jasonxbergman** [comment]
Thank you! I'm standing by eagerly for that release.

**Comment by mrjanerob** [comment]
This is an amazing tool and I hope it gets updated!

**Comment by vingtsunbn** [comment]
we really need it back

**Comment by macskay** [comment]
I uploaded the a temporary release to my repository that can be downloaded and manually installed.
https://github.com/macskay/simplefog/releases/tag/v11-fix

Beware that I will delete this release as soon as the PR I opened for this fix is merged back to the main repository.

**Comment by jasonxbergman** [comment]
Can confirm that this manual installation works! Thanks so much for the quick fix!

**Comment by Moonshaft** [comment]
I followed the instructions that were provided in the v11-fix link above (except I couldn't just extract the zip into my modules folder because it didn't work, it needed to be in it's own simplefog folder), but now I can't seem to move any tokens on my map if the fog is enabled. If I disable the fog, tokens can be dragged around appropriately. I tried resetting the fog on the level as well, but no dice.
There's no conflict with other mods as I've tested this with simplefog being the only mod active. I'm also not getting any errors in the console and double clicking on the pog will not open the sheet associated with it.
![image](https://github.com/League-of-Foundry-Developers/simplefog/assets/20808506/add24802-19ae-4a65-a982-6b11571d7786)

Edit: I can highlight them if I click and drag to select multiple targets at once. I can also rotate them in place with shift-mouse wheel. The moment I click and hold to try and drag the token elsewhere I just get a select box and the token refuses to drag. The example below is the best I can do. Curiously, I seem to be able to still use the arrow keys to move them...
![image](https://github.com/League-of-Foundry-Developers/simplefog/assets/20808506/7a129808-2fd9-45d0-a771-8844665e8bc7)

**Comment by jasonxbergman** [comment]
Can confirm, I'm seeing the same issue. Hopefully it's an easy fix. We're so close!

**Comment by MisterCheesy** [comment]
Same issue

**Comment by thadrine** [comment]
Get random screen flickering when enabled in v11.

**Comment by UranusBytes** [comment]
I had a few mins to play around with the fix from @macskay on a new 11.302 install with a new DND5e 2.2.1 world and scene, and also had the problem as described by @Moonshaft .  As best as I can tell, this is a canvas group and/or zindex problem.  A temp way to see this is go to Simplefog settings (Game Settings -> Configure Settings -> Simplefog) and change the value for **Simplefog Z-index** to **99** (below the tokens layer of 100)

<img width="404" alt="image" src="https://github.com/League-of-Foundry-Developers/simplefog/assets/11236319/16bb7a21-fa52-4a5b-bd49-474a266a9c42">

However, it's been so long since I've dug into the code that I don't fully remember what the consequences are for setting the Z-index so low.  Since both the TokenLayer and the SimplefogLayer are in the InterfaceCanvasGroup, setting the Z-index to 99 _should_ be making the tokens appear on top of Simplefog, but this doesn't seem to be the case.  I don't know/remember why and need to dig in further to figure out why...  One consequence is that the token HUD (name, resource bars, controls when right-clicking on token) are appearing over the simplefog...

**Comment by pj-squirrel** [comment]
To add to that: While I can select and move tokens, when I change the Simplefog Z-Index to 99, that doesn't seem to work with drawings, even when I set their Z-Index to higher values.

**Comment by MisterCheesy** [comment]
Hi, any updates?

**Comment by mattd** [comment]
@macskay I've opened a PR that updates some interaction settings that the new PixiJS version needs to allow for proper selection of tokens. If you can merge that PR into yours, I _think_ we'll be good to go for v11. /cc @UranusBytes

**Comment by Tallon159** [comment]
I tested both fixes and it's working well. I didn't test all the settings but all the tools are working and you can select token and move them.

**Comment by Qenthel94** [comment]
> I uploaded the a temporary release to my repository that can be downloaded and manually installed. https://github.com/macskay/simplefog/releases/tag/v11-fix
> 
> Beware that I will delete this release as soon as the PR I opened for this fix is merged back to the main repository.

Is it possible to install it on Forge?

**Comment by bryancasler** [comment]
This is working for me! Thanks for everyone who helped get it here. Here is what I did:

1. Remove or replace your the latest Simplefog module with: https://github.com/macskay/simplefog/releases/tag/v11-fix
2. Re-activated the Simplefog module
3. Change the z-index setting on Simplefog from 220 to 99
4. Reload Foundry <- You won't see it take affect until you reload Foundry

**Comment by MisterCheesy** [comment]
@bryancasler Did you try selecting anything?   I did a manual merge of the branch you mentioned and the additions like @dmizrahi, and I found everything working.  Now to just get the repo owner to accept all the merges...

**Comment by pj-squirrel** [comment]
I installed the fix and can use (mostly) everything normally, including moving tokens, but I still can't select drawings (like circles etc) or have them shown above the fog layer.

**Comment by bryancasler** [comment]
I only tried selecting tokens, which worked. I don't have any scenes with drawings.

**Comment by APen-FPT** [comment]
> I installed the fix and can use (mostly) everything normally, including moving tokens, but I still can't select drawings (like circles etc) or have them shown above the fog layer.

I have the same problem, using this fix https://github.com/macskay/simplefog/releases/tag/v11-fix.  I can select and move tokens but not select or move drawings.

**Comment by apsiapina** [comment]
> I uploaded the a temporary release to my repository that can be downloaded and manually installed. https://github.com/macskay/simplefog/releases/tag/v11-fix

How would one install this version when using The Forge?

**Comment by UranusBytes** [comment]
v0.3.4 with fixes has been posted.  Extra special thanks to @macskay and @mattd for making this happen.  If ANYTHING isn't working as expected, please let me know ASAP...

**Comment by steveculshaw** [comment]
@UranusBytes Just checked over on the Foundry packages page, and Simple Fog is still showing latest as version 0.3.0 for v10 ???

**Comment by UranusBytes** [comment]
A request is in to League to update the package page, though it can
sometimes take them a couple of days to respond.  You can install by using
the manifest URL from the release

**Comment by steveculshaw** [comment]
Many thanks ... downloaded and manually installed Ok
