### ISSUE TITLE
Simple Fog canvas-layer-control button unresponsive and reveal tool remains active even when simple fog not active

### ISSUE THREAD

**Issue by MNBlockhead** [League-of-Foundry-Developers/simplefog#12]
This is 100% repeatable for me:

1. Open a scene.
2. Click on the Simple Fog icon in the left vertical menu (canvas layer controls)
3. Turn on fog, reveal a section of map, drop character icons
4. Click on a different canvas-layer-control icon, such as the Tokens Layer
5. Click on the Simple Fog layer icon.  NOTHING HAPPENS.  

I am unable to get back to the Simple Fog control unless I refresh my screen. 

Also, if I applied FOW with Simple fog and select a reveal tool, then switch to a different canvas layer control, such as the Tokens Layer, the reveal tool is still active. But there is no way to change to a different reveal tool (e.g. from brush to grid) because the Simple Fog icon is not responsive. 

Also, after applying fog (clicking on the "eye" icon in the Simple Fog layer menu, I often have to refresh the browser before the fog is applied and before reveal controls can be used. 

Do to the need to constantly refresh the browser, Simple Fog has become impractical to use.

**Comment by crhampton1** [comment]
Hey @MNBlockhead, sorry you are having trouble. This sounds like the issues we corrected a while back but just want to verify first. Can you verify that you are on version 0.1.16 of SimpleFog?

If not, we had to fork this repo from the original owner due to him not having time to keep updated. If you are still on his fork it will probably cap at 0.1.11 and say up to date. You will have to uninstall his and then reinstall the current fork, so that it gets you to 0.1.16. You can use this link when adding the module: https://raw.githubusercontent.com/League-of-Foundry-Developers/simplefog/master/module.json

If you are on 0.1.16, let me know, and we can start working on figuring out what is causing this.

**Comment by MNBlockhead** [comment]
It was 0.1.16.  I had uninstalled the prior version (Vance version) and installed the new LoED version.  But I just uninstalled and reinstalled again, and it seems to be working.  I also uninstalled the Less Fog module. Not sure if uninstalling Less Fog made a difference or if it was just uninstalling and reinstalling Simple Fog that fixed it. Anway, seems to be working now.

**Comment by akrigline** [comment]
Your can now simply uninstall and reinstall via the foundry module manager ui. Updating is not the same though.

E: oh you got this sorted in the time it took me to type that. Excellent.

**Comment by crhampton1** [comment]
Thanks! I'll do some research and see if Less Fog causes any weirdness and if there is anything we can do about it. 

Thanks!!
