### ISSUE TITLE
no hidden actors

### ISSUE THREAD

**Issue by ProfTD** [League-of-Foundry-Developers/simplefog#20]
Thanks first of all for the great module. But now to my problem. Compared to the regular Fog of War, Simple Fog doesn't seem to hide the placed Actors. This unfortunately leads to the problem that when players mouse over the Fog, the mouse cursor icon changes once they are over an Actor hidden in the Fog and therefore players know there has to be something in there. Is there any possibility that Simple Fog could give overdrawn Actors the status "hidden" so that they are not shown?
![Simple fog](https://user-images.githubusercontent.com/78954380/107748619-a254ab80-6d19-11eb-86ff-8c2d1db4581d.png)

**Comment by akrigline** [comment]
I believe there is a GM setting something along the lines of "auto visibility" which should already do what you're asking. Does this not work or am I misinterpreting what that setting is supposed to accomplish?

**Comment by crhampton1** [comment]
@akrigline  Auto visibility has not worked for a while, not since Foundry made those updates to it's layers. It was also causing a ton of bugs so to hot fix I just commented out the already not working feature. I have plans to try and get it back to working, but haven't had much luck.

Thanks @ProfTD for bringing this up, I'll try and see if I can get this back in soon.

**Comment by ProfTD** [comment]
@crhampton1 @akrigline Thank you both for your reply. Understandably, it may not be possible to fix it, if the problem originates from Foundry. Thanks for the great module - I'd probably have a crisis with the native Fog of War, as it limits you too much. Keep up the good work :-)
